### ISSUE TITLE
Better Readme

### ISSUE THREAD

**Issue by lfarah** [rimh/RippleTransition#1]
Hey @rimh, your library is really interesting.

The only problem I found was the `README.md`, which lacks information
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to better organize.
If you want, I can help you to organize the lib.

What are your thoughts?

**Comment by rimh** [comment]
@lfarah, sorry for late reply and thank you for your suggestion. It is a nice idea. Thank you for your cooperation in advance.
